---
- hosts: localhost
  connection: local
  vars:
    # sudo everything except brew
    # should_be_root:  "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  # become: true

  tasks:
  - name: install pyenv
    package:
      name: chezmoi


  # tasks:
  # - name: Install collection community.general
  # community.general.ansible_galaxy_install:
  #   type: collection
  #   name: community.general